# This section use by spring mvc
spring:
  http:
    # Chararcter Encoding filter settings
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
endpoints.trace.enabled: false
# All server's configuration here
server:
  # This server instance's port
  port: 8080

# Application settings for your own project
app:
  # Debug flag to figure our whether its in debug mode
  debug: true
  # Redis setting
  redis:
    example:
      host: 
      port: 
      user: 
      passwd: 
  # When you use the Spring provider cache manager, this will help
  cache:
    url: 
  # Mongo section
  mongo:
    example:
      replica.set: 
      host: 
      port: 
      db: 
      user: 
      passwd: 
      conn_timeout: 30000
      wait_timeout: 30000
      write_timeout: 10000
      slave_ok: true
      keep_alive: true
      conn_per_host: 
  # Mybatis Section
  mybatis:
    example:
      db:
      user:
      passwd: